# Generated by Django 5.1.6 on 2025-03-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact_contact',
        ),
    ]
